spring.application.name=expense-tracker

# Database Configuration
spring.datasource.url=postgresql://expense_user:HQDPizPaSyBGqw9sRWqhCOtrI79oWvlK@dpg-d8tc57cm0tmc73c6uq50-a/expense_tracker_0jrq
spring.datasource.username=expense_user
spring.datasource.password=HQDPizPaSyBGqw9sRWqhCOtrI79oWvlK

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080