spring.application.name=expense-tracker

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8tc57cm0tmc73c6uq50-a.virginia-postgres.render.com:5432/expense_tracker_0jrq
spring.datasource.username=expense_user
spring.datasource.password=HQDPizPaSyBGqw9sRWqhCOtrI79oWvlK
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=${PORT:8080}